import { test, expect } from '@playwright/test';
test('desktop: register, seed actual Mongo records, execute, change supplier, approve, replan, verify, analytics and audit', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /Supply operations/ })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/landing.png', fullPage: true });
  await page.getByRole('link', { name: 'Open workspace' }).click();
  await page.getByLabel('Full name').fill('Demo Operator');
  await page.getByLabel('Work email').fill(`browser-${Date.now()}@example.com`);
  await page.getByLabel(/^Password/).fill('browser-password-123');
  await page.getByRole('button', { name: 'Create workspace' }).click();
  await expect(page.getByRole('heading', { name: /Good to see you/ })).toBeVisible();
  await expect(page.getByText(/TEST FIXTURE execution/)).toBeVisible();
  await page.getByRole('link', { name: 'Business context', exact: true }).click();
  await page.getByRole('button', { name: 'Initialize demo data' }).click();
  await expect(page.getByText('Atlas Components')).toBeVisible();
  await page.getByRole('link', { name: 'New workflow', exact: true }).first().click();
  await page.getByRole('checkbox').nth(0).check(); await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('button', { name: 'Create workflow', exact: true }).click();
  await page.getByRole('button', { name: 'Start test execution' }).click();
  await expect(page.getByRole('button', { name: 'Approve purchase' })).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('heading', { name: '$660.00' })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/approval-test-fixture.png', fullPage: true });
  await page.getByRole('button', { name: 'Withdraw quoted supplier stock' }).click();
  await page.getByRole('button', { name: 'Approve purchase' }).click();
  await page.getByRole('button', { name: 'Confirm decision' }).click();
  await expect(page.getByRole('heading', { name: '$792.00' })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: 'Approve purchase' }).click();
  await page.getByRole('button', { name: 'Confirm decision' }).click();
  await expect(page.getByRole('heading', { name: 'Workflow evidence' })).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole('heading', { name: 'Final operations report' })).toBeVisible();
  await page.getByRole('tab', { name: 'History' }).click();
  await expect(page.getByText('QUOTE_CHANGED', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Plan revision 2' })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/workflow-test-fixture.png', fullPage: true });
  await page.getByRole('link', { name: 'Analytics', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Autonomy, measured.' })).toBeVisible();
  await page.getByRole('link', { name: 'Audit trail', exact: true }).click();
  await expect(page.getByText('Workflow completed', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Overview', exact: true }).click();
  await expect(page.locator('table').getByText(/Recover both urgent/)).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/dashboard-test-fixture.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('mobile: protected routes, responsive registration and accessible navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/app/workflows'); await expect(page).toHaveURL(/login/);
  await page.goto('/register');
  await page.getByLabel('Full name').fill('Mobile Operator');
  await page.getByLabel('Work email').fill(`mobile-${Date.now()}@example.com`);
  await page.getByLabel(/^Password/).fill('mobile-password-123');
  await page.getByRole('button', { name: 'Create workspace' }).click();
  await expect(page.getByRole('heading', { name: /Good to see you/ })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('link', { name: 'Approval center' }).click();
  await expect(page.getByRole('heading', { name: 'No pending approvals' })).toBeVisible();
  await page.screenshot({ path: 'docs/screenshots/mobile-test-fixture.png', fullPage: true });
});
