import { assert } from '../utils/errors.js';
const transitions = {
  CREATED: ['PLANNING', 'CANCELLED'], PLANNING: ['PLANNED', 'ANALYZING_FAILURE', 'CANCELLED'],
  PLANNED: ['EXECUTING', 'ANALYZING_FAILURE', 'CANCELLED'],
  EXECUTING: ['VERIFYING', 'WAITING_FOR_TOOL', 'COMPLETED', 'ANALYZING_FAILURE', 'CANCELLED'],
  WAITING_FOR_TOOL: ['EXECUTING', 'VERIFYING', 'WAITING_FOR_APPROVAL', 'ANALYZING_FAILURE', 'CANCELLED'],
  WAITING_FOR_APPROVAL: ['EXECUTING', 'REPLANNING', 'CANCELLED'],
  VERIFYING: ['WAITING_FOR_TOOL', 'EXECUTING', 'ANALYZING_FAILURE', 'CANCELLED'],
  ANALYZING_FAILURE: ['RETRYING', 'REPLANNING', 'ESCALATED', 'CANCELLED'],
  RETRYING: ['EXECUTING', 'ANALYZING_FAILURE', 'CANCELLED'],
  REPLANNING: ['PLANNED', 'ANALYZING_FAILURE', 'CANCELLED'],
  COMPLETED: [], CANCELLED: [], ESCALATED: [],
};
export function validateTransition(from, to) {
  assert(from === to || transitions[from]?.includes(to), 'INVALID_STATE_TRANSITION', `Cannot transition from ${from} to ${to}`, 409);
}
