import { Box, Stack, Typography } from '@mui/material';
import { CheckCircle2, GitBranch, Zap, Timer } from 'lucide-react';
import { PageHeader, ResourceState, Panel, MetricCard, RateBar } from '../components/common';
import { useResource } from '../hooks/useResource';
import { percent, duration, label } from '../utils/format';
export default function Analytics() {
  const resource = useResource('/analytics', 5000); const m = resource.data;
  return <><PageHeader title="Autonomy, measured." description="Metrics computed from your workflow, tool, agent and approval records." /><ResourceState resource={resource}>{m && <><Box className="four-grid" mb={3}>
    <MetricCard title="Verified completions" value={m.completedTasks} detail={`${m.totalTasks} workflows created`} icon={CheckCircle2} /><MetricCard title="Automation rate" value={percent(m.automationRate)} detail={`${m.uniqueSuccessfulActions} unique successful actions`} icon={Zap} /><MetricCard title="Replanned workflows" value={m.replannedTasks} detail="Tasks with more than one stored plan" icon={GitBranch} /><MetricCard title="Average completion" value={duration(m.averageCompletionMs)} detail="Includes human approval waiting time" icon={Timer} />
  </Box><Box className="two-grid"><Panel title="Execution reliability"><Stack spacing={3} p={3}><RateBar label="Workflow success" value={m.workflowSuccessRate} /><RateBar label="Tool success" value={m.toolSuccessRate} /><RateBar label="Tool failure" value={m.toolFailureRate} /><RateBar label="Failure recovery" value={m.failureRecoveryRate} /><Typography variant="body2" color="text.secondary">{m.toolAttempts} finished tool attempts · {m.replannedTasks} replanned workflows</Typography></Stack></Panel>
    <Panel title="Human involvement"><Stack spacing={3} p={3}><RateBar label="Automatic action rate" value={m.automationRate} /><RateBar label="High-risk approved action rate" value={m.humanInterventionRate} /><RateBar label="Approval acceptance rate" value={m.approvalRate} /><Typography variant="body2" color="text.secondary">{m.decidedApprovals} decisions recorded · {m.pendingApprovals} pending</Typography></Stack></Panel></Box>
    <Panel title="Agent executions" subtitle="Each bar represents actual validated model invocations" sx={{ mt: 3 }}><Stack p={3} spacing={2.5}>{m.agentActivity.map(a => <Stack key={a.agent} direction="row" alignItems="center" gap={2}><Typography variant="body2" width={115}>{label(a.agent)}</Typography><Box flex={1} sx={{ bgcolor: '#eef2f4', height: 13, borderRadius: 1, overflow: 'hidden' }}><Box sx={{ height: '100%', bgcolor: '#367b6b', width: `${a.completed / Math.max(1, ...m.agentActivity.map(v => v.completed)) * 100}%` }} /></Box><Typography variant="caption" width={135}>{a.completed} valid · {a.failed} failed</Typography></Stack>)}</Stack></Panel>
    <Panel title="Metric definitions" subtitle="Empty denominators are shown as — rather than 0%" sx={{ mt: 3 }}><Stack spacing={2} p={3}>{Object.entries(m.definitions).map(([name, text]) => <Box key={name}><Typography variant="body2" fontWeight={650}>{name}</Typography><Typography variant="body2" color="text.secondary" mt={0.5}>{text}</Typography></Box>)}</Stack></Panel>
  </>}</ResourceState></>;
}
