import { useState } from 'react';
import { Alert, Box, Button, Chip, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material';
import { Database, Package, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader, ResourceState, Panel, EmptyState, JsonDetails } from '../components/common';
import { useResource } from '../hooks/useResource';
import { useToast } from '../context/ToastContext';
import { api } from '../services/api';
import { currency, date } from '../utils/format';
export default function Business() {
  const resource = useResource('/business', 4000); const toast = useToast(); const [busy, setBusy] = useState(false); const business = resource.data?.business;
  const importFile = async e => {
    const file = e.target.files?.[0]; if (!file) return;
    setBusy(true); try {
      if (file.size > 32768) throw new Error('Business JSON must be smaller than 32 KB.');
      await api('/business/import', { method: 'POST', body: JSON.parse(await file.text()) });
      toast('Your business records were imported.'); resource.reload();
    } catch (error) { toast(error.message, 'error'); } finally { setBusy(false); e.target.value = ''; }
  };
  const initialize = async () => {
    setBusy(true); try { await api('/business/initialize', { method: 'POST', body: {} }); toast('Demo business records created. No workflow history was seeded.'); resource.reload(); } catch (e) { toast(e.message, 'error'); } finally { setBusy(false); }
  };
  return <><PageHeader title="Business context" description="The actual records agents inspect and mutate. Seed inputs are labeled; execution records are live." action={<Button component={Link} to="/app/workflows/new" endIcon={<ArrowRight size={17} />}>Create a goal</Button>} /><ResourceState resource={resource}>
    {!business ? <Panel><EmptyState icon={Database} title="Initialize your sandbox business" description="Create two urgent orders, eight on-hand units, and three competing suppliers, or import your own JSON records. Execution history starts empty." action={<Stack direction="row" flexWrap="wrap" gap={1}><Button variant="contained" disabled={busy} onClick={initialize}>{busy ? 'Creating records…' : 'Initialize demo data'}</Button><Button variant="outlined" component="label" disabled={busy}>Import business JSON<input type="file" accept="application/json,.json" hidden onChange={importFile} /></Button></Stack>} /></Panel> : <>
      <Alert severity="info" sx={{ mb: 3 }}>Business inputs are {business.seeded ? 'demo seed data' : 'user-imported data'}. Reservations, purchases, allocations, reports and memory are genuine persisted application operations. Purchasing commits scheduled supply; it does not order from an external supplier.</Alert>
      <Box className="two-grid"><Panel title="Inventory" action={<Chip label={`${business.seeded ? 'DEMO' : 'IMPORTED'} INPUT / LIVE BALANCE`} size="small" variant="outlined" />}><Stack p={3} spacing={2}>{business.inventory.map(item => <Stack key={item.sku} direction="row" alignItems="center" gap={2}><Package size={24} color="#17695d" /><Box flex={1}><Typography variant="h6">{item.name}</Typography><Typography color="text.secondary" variant="body2">{item.sku}</Typography></Box><Box textAlign="right"><Typography variant="h2">{item.available}</Typography><Typography variant="caption" color="text.secondary">units on hand</Typography></Box></Stack>)}</Stack></Panel>
        <Panel title="Order demand"><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Order</TableCell><TableCell>Allocated</TableCell><TableCell>Due</TableCell></TableRow></TableHead><TableBody>{business.orders.map(o => <TableRow key={o.id}><TableCell><Typography variant="body2" fontWeight={650}>{o.id}</Typography><Typography variant="caption" color="text.secondary">{o.customer}</Typography></TableCell><TableCell>{o.allocated} / {o.quantity}</TableCell><TableCell>{o.dueDays} days</TableCell></TableRow>)}</TableBody></Table></TableContainer></Panel></Box>
      <Panel title="Supplier options" subtitle="Quotes carry versions; changing availability invalidates saved proposals" sx={{ mt: 3 }}><TableContainer><Table><TableHead><TableRow>{['Supplier', 'Stock', 'Unit cost', 'Lead time', 'Quote version'].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{business.suppliers.map(s => <TableRow key={s.id}><TableCell><Typography variant="body2" fontWeight={650}>{s.name}</Typography><Typography variant="caption" color="text.secondary">{s.id} · {s.sku}</Typography></TableCell><TableCell>{s.available}</TableCell><TableCell>{currency(s.unitCost)}</TableCell><TableCell>{s.leadDays} days</TableCell><TableCell>v{s.version}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Panel>
      <Panel title="Purchase ledger" subtitle="Real committed sandbox purchases created by the execution tool" sx={{ mt: 3 }}>{business.purchases.length ? <TableContainer><Table><TableHead><TableRow><TableCell>Supplier</TableCell><TableCell>Units</TableCell><TableCell>Allocated</TableCell><TableCell>Commitment</TableCell><TableCell>Arrival</TableCell></TableRow></TableHead><TableBody>{business.purchases.map(p => <TableRow key={p.id}><TableCell>{p.supplierId}</TableCell><TableCell>{p.quantity}</TableCell><TableCell>{p.allocated}</TableCell><TableCell>{currency(p.totalCost)}</TableCell><TableCell>{p.leadDays} days</TableCell></TableRow>)}</TableBody></Table></TableContainer> : <EmptyState title="No purchases committed" description="A purchase appears only after the tool passes authorization, risk policy, approval and current business checks." />}</Panel>
      <Panel title="Long-term outcome memory" subtitle="Stored evidence that influences future supplier comparisons" sx={{ mt: 3 }}>{resource.data.memory.length ? <Stack p={2.5} spacing={2}>{resource.data.memory.map(m => <Box key={m._id} className="execution-record"><Chip size="small" label={m.kind} variant="outlined" /><Typography variant="body2" mt={1.5}>{m.summary}</Typography><Typography variant="caption" color="text.secondary">{date(m.createdAt)} · {m.sku}</Typography><JsonDetails title="Source evidence" data={m.evidence} /></Box>)}</Stack> : <EmptyState title="Memory starts with evidence" description="Verified outcomes and genuine supplier failures will be stored here. No invented historical lessons." />}</Panel>
      <Panel title="Internal notifications & reports" sx={{ mt: 3 }}>{business.notifications.length ? <Stack p={2.5} spacing={2}>{business.notifications.map(n => <Box key={n.id}><Typography variant="caption" color="primary">{n.channel} · {date(n.createdAt)}</Typography><Typography variant="body2" mt={1} sx={{ whiteSpace: 'pre-wrap' }}>{n.message}</Typography></Box>)}</Stack> : <EmptyState title="No internal communications yet" description="Agents can persist operations notices and evidence-grounded final reports through authorized tools." />}</Panel>
    </>}
  </ResourceState></>;
}
