import { Box, Button, Container, Divider, Paper, Stack, Typography } from '@mui/material';
import { ArrowRight, Boxes, GitBranch, ShieldCheck, ClipboardCheck, Search, SlidersHorizontal, Zap, FileCheck2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Brand } from '../layouts/AppLayout';
const agents = [
  [Search, 'Research', 'Inventory, demand & context'], [SlidersHorizontal, 'Analysis', 'Quotes, constraints & tradeoffs'],
  [Zap, 'Execution', 'Permitted business actions'], [ShieldCheck, 'Approval', 'A human decision for high risk'],
  [ClipboardCheck, 'Verification', 'Check the actual business state'], [FileCheck2, 'Report', 'Outcome & complete evidence'],
];
export default function Landing() {
  return <Box sx={{ bgcolor: '#fbfcfd', minHeight: '100vh' }}><Container maxWidth="lg"><Stack component="header" direction="row" alignItems="center" justifyContent="space-between" py={3}><Brand /><Stack direction="row" spacing={1}><Button component={Link} to="/login">Sign in</Button><Button variant="contained" component={Link} to="/register">Open workspace</Button></Stack></Stack>
    <Box className="landing-hero"><Box><Typography className="eyebrow" color="primary" mb={2.5}>FROM DISRUPTION TO VERIFIED ACTION</Typography>
      <Typography variant="h1" component="h1" sx={{ fontSize: { xs: '2.7rem', md: '3.8rem' } }}>Supply operations.<br /><span style={{ color: '#17695d' }}>Coordinated.</span></Typography>
      <Typography color="text.secondary" fontSize="1.1rem" lineHeight={1.8} mt={3} maxWidth={500}>When stock runs short, your work shouldn’t multiply. Give StockPilot a goal. Specialized agents plan, coordinate and execute—with approvals where they matter.</Typography>
      <Stack direction="row" spacing={2} mt={4}><Button size="large" variant="contained" component={Link} to="/register" endIcon={<ArrowRight size={18} />}>Start operating</Button><Button component="a" href="#architecture" size="large">See how it works</Button></Stack>
      <Stack direction="row" spacing={2} mt={3} flexWrap="wrap"><Typography variant="body2" color="text.secondary">Real tools</Typography><Typography variant="body2" color="text.secondary">Persistent approvals</Typography><Typography variant="body2" color="text.secondary">Verified outcomes</Typography></Stack></Box>
      <Paper variant="outlined" sx={{ p: { xs: 2.5, md: 3.5 }, bgcolor: '#fff' }}><Stack direction="row" alignItems="center" gap={1} mb={2}><Boxes size={20} color="#17695d" /><Typography variant="h6">The goal-to-action loop</Typography></Stack><Typography variant="body2" color="text.secondary" mb={3}>Architecture overview · not an execution preview</Typography>
        <Box className="architecture-goal"><Typography className="eyebrow">BUSINESS GOAL</Typography><Typography mt={1} fontWeight={600}>Recover urgent orders. Respect budget.<br />Adapt when supplier conditions change.</Typography></Box>
        <Box className="agent-path">{agents.map(([Icon, name, description]) => <Stack key={name} direction="row" spacing={1.5} alignItems="center" className="architecture-node"><Box className="node-icon"><Icon size={17} /></Box><Box><Typography variant="body2" fontWeight={650}>{name}</Typography><Typography variant="caption" color="text.secondary">{description}</Typography></Box></Stack>)}</Box>
        <Stack direction="row" spacing={1} alignItems="center" mt={2} color="primary.main"><GitBranch size={16} /><Typography variant="body2">New observations → revised plan</Typography></Stack></Paper></Box>
    <Divider /><Box id="architecture" py={7}><Typography className="eyebrow" color="primary" mb={1.5}>AN OPERATING SYSTEM, NOT AN ANSWER BOX</Typography><Typography variant="h2" component="h2">Intelligence with an execution trail.</Typography>
      <Box className="three-grid" mt={4}>{[[GitBranch, 'Adapt to reality', 'Plans are generated from your current records and revised after stock changes, tool failures or rejected actions.'], [ShieldCheck, 'Keep authority explicit', 'Every action passes schema validation, role permissions and business rules. High-risk purchases pause for your exact approval.'], [ClipboardCheck, 'Prove the outcome', 'Independent checks validate order allocations, committed spend and deadlines. Inspect every agent decision and tool result.']].map(([Icon, title, text]) => <Box key={title}><Icon size={25} color="#17695d" /><Typography variant="h5" mt={2} mb={1}>{title}</Typography><Typography color="text.secondary" lineHeight={1.8}>{text}</Typography></Box>)}</Box>
    </Box><Paper sx={{ bgcolor: '#111d2e', color: '#fff', p: { xs: 3, md: 5 }, mb: 6 }}><Stack direction={{ xs: 'column', md: 'row' }} alignItems={{ md: 'center' }} justifyContent="space-between" gap={3}><Box><Typography variant="h3" component="h2">Less coordination. More completion.</Typography><Typography color="#a7b6c8" mt={1}>A sandbox business ledger. Live AI planning. Inspectable execution.</Typography></Box><Button component={Link} to="/register" variant="contained" color="secondary" endIcon={<ArrowRight size={17} />}>Create your workspace</Button></Stack></Paper>
    <Stack component="footer" direction="row" justifyContent="space-between" py={3} borderTop="1px solid" borderColor="divider"><Typography variant="body2" color="text.secondary">StockPilot · Agentic AI & Intelligent Systems</Typography><Typography variant="body2" color="text.secondary">Built for evidence.</Typography></Stack></Container></Box>;
}
